apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: milo-os-com-gateway
spec:
  gatewayClassName: datum-external-global-proxy
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: http-milo-os-com-redirect
    port: 80
    protocol: HTTP
    hostname: milo-os.com
  - allowedRoutes:
      namespaces:
        from: Same
    name: http-www-milo-os-com-redirect
    port: 80
    protocol: HTTP
    hostname: www.milo-os.com
  # This listener is used to serve the HTTPS traffic for the milo-os.com
  # domain.
  - allowedRoutes:
      namespaces:
        from: Same
    name: https-milo-os-com-redirect
    port: 443
    protocol: HTTPS
    hostname: milo-os.com
    tls:
      mode: Terminate
      options:
        gateway.networking.datumapis.com/certificate-issuer: auto
  # This listener is used to serve the HTTPS traffic for the www.milo-os.com
  # domain. All other listeners redirect to this domain.
  - allowedRoutes:
      namespaces:
        from: Same
    name: https-www-milo-os-com
    port: 443
    protocol: HTTPS
    hostname: www.milo-os.com
    tls:
      mode: Terminate
      options:
        gateway.networking.datumapis.com/certificate-issuer: auto
