import {
  ArrowRight,
  ArrowLeft,
  BookImage,
  BookOpen,
  BookText,
  CalendarDays,
  CalendarPlus,
  CalendarRange,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleArrowRight,
  Clock,
  Cloud,
  Code,
  Command,
  Database,
  FileText,
  GitBranch,
  GitCommit,
  GitCompare,
  GitMerge,
  GitPullRequest,
  Github,
  Globe,
  Goal,
  Heart,
  HeartHandshake,
  Key,
  KeyRound,
  Link,
  Linkedin,
  ListRestart,
  Lock,
  LockOpen,
  Menu,
  MessageSquarePlus,
  Minus,
  Network,
  Paintbrush,
  Plus,
  Power,
  Presentation,
  Search,
  Server,
  Settings,
  Shield,
  Shirt,
  Slack,
  Star,
  Terminal,
  Twitter,
  User,
  Users,
  Video,
  WalletMinimal,
  Webhook,
  X,
  Zap,
} from 'lucide-astro';

// Icon mapping object
const iconMap = {
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'book-image': BookImage,
  'book-open': BookOpen,
  'book-text': BookText,
  'calendar-days': CalendarDays,
  'calendar-plus': CalendarPlus,
  'calendar-range': CalendarRange,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-arrow-right': CircleArrowRight,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  command: Command,
  database: Database,
  'file-text': FileText,
  'git-branch': GitBranch,
  'git-commit': GitCommit,
  'git-compare': GitCompare,
  'git-merge': GitMerge,
  'git-pull-request': GitPullRequest,
  github: Github,
  globe: Globe,
  goal: Goal,
  heart: Heart,
  'heart-handshake': HeartHandshake,
  key: Key,
  'key-round': KeyRound,
  link: Link,
  linkedin: Linkedin,
  'list-restart': ListRestart,
  lock: Lock,
  'lock-open': LockOpen,
  menu: Menu,
  'message-square-plus': MessageSquarePlus,
  minus: Minus,
  network: Network,
  paintbrush: Paintbrush,
  plus: Plus,
  power: Power,
  presentation: Presentation,
  search: Search,
  server: Server,
  settings: Settings,
  shield: Shield,
  shirt: Shirt,
  slack: Slack,
  star: Star,
  terminal: Terminal,
  twitter: Twitter,
  user: User,
  users: Users,
  video: Video,
  'wallet-minimal': WalletMinimal,
  webhook: Webhook,
  x: X,
  zap: Zap,
} as const;

// Icon mapping function
export const getIcon = (iconName: string) => {
  return iconMap[iconName as keyof typeof iconMap] || null;
};

// Type for icon names
export type IconName = keyof typeof iconMap;
