apiVersion: compute.datumapis.com/v1alpha
kind: Workload
metadata:
  name: milo-os-com
spec:
  template:
    spec:
      runtime:
        resources:
          instanceType: datumcloud/d1-standard-2
        sandbox:
          containers:
            - name: app
              image: index.unikraft.io/datum/milo-os-com:slim
              env:
                - name: NODE_ENV
                  value: production
                - name: PORT
                  value: "4321"
                - name: SITE_URL
                  value: "https://www.milo-os.com/"
                - name: APP_ID
                  valueFrom:
                    secretKeyRef:
                      name: milo-os-com-secrets
                      key: APP_ID
                - name: APP_INSTALLATION_ID
                  valueFrom:
                    secretKeyRef:
                      name: milo-os-com-secrets
                      key: APP_INSTALLATION_ID
                - name: APP_PRIVATE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: milo-os-com-secrets
                      key: APP_PRIVATE_KEY
              ports:
                - name: http
                  port: 4321
                  protocol: TCP
      networkInterfaces:
        - network:
            name: default
  placements:
    - name: us
      cityCodes:
        - DFW
      scaleSettings:
        minReplicas: 1
        instanceManagementPolicy: OrderedReady
